### ISSUE TITLE
Question regarding equation 1

### ISSUE THREAD

**Issue by bhat-prashant** [neu-spiral/SparCL#1]
We read your fantastic paper recently. In equation 1, we see that you have three terms namely: absolute weight, weighted gradients of masked and unmasked losses with respect to weights. 
However, when prune updated is called (main_sparse_train_w_data_gradient_efficient.py#L876), the gradients seem to be zero and have no impact on Equation 1. Please let us know how Equation 1 is being computed without gradients. 

Thanks in advance,

Reference:
https://github.com/neu-spiral/SparCL/blob/main/prune_utils/utils_pr.py#L106

**Comment by KingSpencer** [comment]
Hi,

Thanks for your interest in our paper!

1. We merged the later two terms to simplify the logic when $\alpha = \beta$.
2. We mistakenly upload a wrong version when doing code clean-up. We have addressed the issue and thank you again for your great catch!

Best,
Zifeng and Zheng
